import { useCallback, useEffect, useState } from 'react';
import type { Variant } from '../types/variant';
import { snapCompleteService } from '../services/snapCompleteService';

interface OwnedVariantsFile {
  ownedIds: string[];
  acquisitionDates?: Record<string, string>;
  count: number;
  importedAt: string;
}

interface CostDataEntry {
  id: string;
  bundleName?: string;
  goldCost?: number;
  tokenCost?: number;
}

interface CostDataFile {
  entries: CostDataEntry[];
  count: number;
  importedAt: string;
}

export interface UseVariantsData {
  allVariants: Variant[];
  ownedIds: Set<string>;
  // Real in-game acquisition date per owned variant (from
  // CollectionState.json -> ServerState.Cards[].TimeCreated), distinct from
  // when a card was added to a list in this app.
  acquisitionDates: Record<string, string>;
  loading: boolean;
  loadError: boolean;
  /** Re-run the load (the load-error screen's "Riprova" button). */
  retry: () => void;
}

// Loads the card database + this account's owned cards and shop/vault
// costs. Bulk variants come from snapCompleteService, which caches them in
// localStorage and only re-downloads variants.json when the version in
// variants-meta.json changes (see snapCompleteService.ts). Owned variants
// come from public/owned-variants.json, generated by `npm run import-owned`
// from the Marvel Snap save file (CollectionState.json), and are also
// cached/versioned the same way.
export function useVariantsData(): UseVariantsData {
  const [allVariants, setAllVariants] = useState<Variant[]>([]);
  const [ownedIds, setOwnedIds] = useState<Set<string>>(new Set());
  const [acquisitionDates, setAcquisitionDates] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  const [reloadNonce, setReloadNonce] = useState(0);

  useEffect(() => {
    const loadVariants = async () => {
      setLoading(true);
      setLoadError(false);

      let variants: Variant[];
      try {
        variants = await snapCompleteService.getAllVariants();
      } catch {
        // No data and no usable cache - show a retryable error instead of
        // hanging on the loading screen.
        setLoadError(true);
        setLoading(false);
        return;
      }

      // Merge in cost data, when present, from public/cost-data.json
      // (generated by `npm run import-costs` from the Marvel Snap shop save).
      // Coverage is partial by nature - only variants recently seen in this
      // account's shop/vault will have this data.
      try {
        const costResponse = await fetch('/cost-data.json', { cache: 'no-store' });
        if (costResponse.ok) {
          const costFile: CostDataFile = await costResponse.json();
          const costById = new Map(costFile.entries.map((e) => [e.id, e]));
          variants = variants.map((v) => {
            const cost = costById.get(v.id);
            return cost
              ? { ...v, bundleName: cost.bundleName, goldCost: cost.goldCost, tokenCost: cost.tokenCost }
              : v;
          });
        }
      } catch {
        // No cost data available - not fatal, cards just won't show a bundle name.
      }

      setAllVariants(variants);

      // Load owned variants: prefer the freshly-imported file if present,
      // otherwise fall back to whatever was cached locally before.
      try {
        const response = await fetch('/owned-variants.json', { cache: 'no-store' });
        if (response.ok) {
          const data: OwnedVariantsFile = await response.json();
          setOwnedIds(new Set(data.ownedIds));
          localStorage.setItem('marvelSnapOwned', JSON.stringify(data.ownedIds));
          if (data.acquisitionDates) {
            setAcquisitionDates(data.acquisitionDates);
            localStorage.setItem('marvelSnapAcquisitionDates', JSON.stringify(data.acquisitionDates));
          }
        } else {
          throw new Error('owned-variants.json not found');
        }
      } catch {
        const savedOwned = localStorage.getItem('marvelSnapOwned');
        if (savedOwned) {
          setOwnedIds(new Set(JSON.parse(savedOwned)));
        }
        const savedAcquisitionDates = localStorage.getItem('marvelSnapAcquisitionDates');
        if (savedAcquisitionDates) {
          setAcquisitionDates(JSON.parse(savedAcquisitionDates));
        }
      }

      setLoading(false);
    };

    loadVariants();
  }, [reloadNonce]);

  const retry = useCallback(() => setReloadNonce((n) => n + 1), []);

  return { allVariants, ownedIds, acquisitionDates, loading, loadError, retry };
}
