import { useCallback, useEffect, useState } from 'react';
import type { Variant } from '../types/variant';
import { snapCompleteService } from '../services/snapCompleteService';

interface OwnedVariantsFile {
  ownedIds: string[];
  acquisitionDates?: Record<string, string>;
  count: number;
  importedAt: string;
}

interface CostDataEntry {
  id: string;
  bundleName?: string;
}

interface CostDataFile {
  entries: CostDataEntry[];
  count: number;
  importedAt: string;
}

export interface UseVariantsData {
  allVariants: Variant[];
  ownedIds: Set<string>;
  // Real in-game acquisition date per owned variant (from
  // CollectionState.json -> ServerState.Cards[].TimeCreated), distinct from
  // when a card was added to a list in this app.
  acquisitionDates: Record<string, string>;
  loading: boolean;
  loadError: boolean;
  /** Re-run the load (the load-error screen's "Riprova" button). */
  retry: () => void;
}

// Loads the card database + this account's owned cards and shop/vault
// costs. Bulk variants come from snapCompleteService, which caches them in
// localStorage and only re-downloads variants.json when the version in
// variants-meta.json changes (see snapCompleteService.ts). Owned variants
// come from public/owned-variants.json, generated by `npm run import-owned`
// from the Marvel Snap save file (CollectionState.json), and are also
// cached/versioned the same way.
export function useVariantsData(): UseVariantsData {
  const [allVariants, setAllVariants] = useState<Variant[]>([]);
  const [ownedIds, setOwnedIds] = useState<Set<string>>(new Set());
  const [acquisitionDates, setAcquisitionDates] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  const [reloadNonce, setReloadNonce] = useState(0);

  useEffect(() => {
    const loadVariants = async () => {
      setLoading(true);
      setLoadError(false);

      let variants: Variant[];
      try {
        variants = await snapCompleteService.getAllVariants();
      } catch {
        // No data and no usable cache - show a retryable error instead of
        // hanging on the loading screen.
        setLoadError(true);
        setLoading(false);
        return;
      }

      // Merge in the bundle name, when present, from public/cost-data.json
      // (generated by `npm run import-costs` from the Marvel Snap shop
      // save). Gold/token price isn't merged from here - every card of a
      // tier costs the same fixed amount (see utils/tierPrices.ts), so
      // there's nothing per-account to merge for that part.
      try {
        const costResponse = await fetch('/cost-data.json', { cache: 'no-store' });
        if (costResponse.ok) {
          const costFile: CostDataFile = await costResponse.json();
          const costById = new Map(costFile.entries.map((e) => [e.id, e]));
          variants = variants.map((v) => {
            const cost = costById.get(v.id);
            return cost?.bundleName ? { ...v, bundleName: cost.bundleName } : v;
          });
        }
      } catch {
        // No cost data available - not fatal, cards just won't show a bundle name.
      }

      // Load owned variants: prefer the freshly-imported file if present,
      // otherwise fall back to whatever was cached locally before.
      let owned = new Set<string>();
      let acquired: Record<string, string> = {};
      try {
        const response = await fetch('/owned-variants.json', { cache: 'no-store' });
        if (response.ok) {
          const data: OwnedVariantsFile = await response.json();
          owned = new Set(data.ownedIds);
          localStorage.setItem('marvelSnapOwned', JSON.stringify(data.ownedIds));
          if (data.acquisitionDates) {
            acquired = data.acquisitionDates;
            localStorage.setItem('marvelSnapAcquisitionDates', JSON.stringify(data.acquisitionDates));
          }
        } else {
          throw new Error('owned-variants.json not found');
        }
      } catch {
        const savedOwned = localStorage.getItem('marvelSnapOwned');
        if (savedOwned) owned = new Set(JSON.parse(savedOwned));
        const savedAcquisitionDates = localStorage.getItem('marvelSnapAcquisitionDates');
        if (savedAcquisitionDates) acquired = JSON.parse(savedAcquisitionDates);
      }

      // A card you own is out, whatever SnapComplete says: Promo/LTGM cards
      // often have no listed release date (or a 2099 placeholder) even though
      // players already have them. Fall back to the acquisition date so they
      // still sort sensibly by release date.
      const now = Date.now();
      variants = variants.map((v) => {
        if (!owned.has(v.id) || v.releaseStatus === 'released') return v;
        const dateIsReal = v.releaseDate && new Date(v.releaseDate).getTime() <= now;
        return {
          ...v,
          releaseStatus: 'released',
          releaseDate: dateIsReal ? v.releaseDate : acquired[v.id] ?? undefined,
        };
      });

      setAllVariants(variants);
      setOwnedIds(owned);
      setAcquisitionDates(acquired);
      setLoading(false);
    };

    loadVariants();
  }, [reloadNonce]);

  const retry = useCallback(() => setReloadNonce((n) => n + 1), []);

  return { allVariants, ownedIds, acquisitionDates, loading, loadError, retry };
}
