import { useCallback, useMemo, useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import type { Variant } from './types/variant';
import Navigation from './components/Navigation';
import VariantsList from './components/VariantsList';
import UnreleasedCards from './components/UnreleasedCards';
import SettingsPage from './components/SettingsPage';
import { useTabs } from './hooks/useTabs';
import { useListStore } from './hooks/useListStore';
import { useStatusStyles } from './hooks/useStatusStyles';
import { useBadgeColors } from './hooks/useBadgeColors';
import { useCardColumns } from './hooks/useCardColumns';
import { getVariantPrice } from './utils/tierPrices';
import { snapCompleteService } from './services/snapCompleteService';
import './App.css';

interface OwnedVariantsFile {
  ownedIds: string[];
  acquisitionDates?: Record<string, string>;
  count: number;
  importedAt: string;
}

interface CostDataEntry {
  id: string;
  bundleName?: string;
  goldCost?: number;
  tokenCost?: number;
}

interface CostDataFile {
  entries: CostDataEntry[];
  count: number;
  importedAt: string;
}

function App() {
  const [allVariants, setAllVariants] = useState<Variant[]>([]);

  // Tab config (order, names, which lists exist) + the id-lists themselves.
  const tabs = useTabs();
  const listStore = useListStore(tabs.listKeys);
  const statusStyles = useStatusStyles();
  const badgeColors = useBadgeColors();
  // Lifted out of VariantsList so the nav logo ("VARIANTS" -> Wishlist) can
  // set it directly, regardless of which route is currently mounted.
  const [activeTabId, setActiveTabId] = useState<string>(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('marvelSnapListView') || '{}');
      return saved.activeTabId ?? 'wishlist';
    } catch {
      return 'wishlist';
    }
  });

  // Delete a tab and, if it was a list, drop its stored data too.
  const deleteTab = useCallback(
    (id: string) => {
      const tab = tabs.tabs.find((t) => t.id === id);
      tabs.remove(id);
      if (tab?.listKey) listStore.destroy(tab.listKey);
    },
    [tabs, listStore]
  );

  const wishlistKey = useMemo(
    () => tabs.tabs.find((t) => t.kind === 'wishlist')?.listKey,
    [tabs.tabs]
  );
  const wishlistCount = wishlistKey ? listStore.list(wishlistKey).size : 0;
  const wishlistIds = wishlistKey ? listStore.list(wishlistKey).ids : undefined;
  const listTabs = useMemo(() => tabs.tabs.filter((t) => t.kind !== 'view'), [tabs.tabs]);

  // Total gold/tokens to buy every wishlisted card - confirmed price where
  // known, otherwise its rarity/vault tier's fixed price; cards with
  // neither (unreleased, or a real-money-only source) don't contribute.
  const wishlistCost = useMemo(() => {
    if (!wishlistIds || wishlistIds.length === 0) return { gold: 0, token: 0 };
    const set = new Set(wishlistIds);
    let gold = 0;
    let token = 0;
    for (const variant of allVariants) {
      if (!set.has(variant.id)) continue;
      const price = getVariantPrice(variant);
      if (!price) continue;
      if (price.currency === 'gold') gold += price.amount;
      else token += price.amount;
    }
    return { gold, token };
  }, [allVariants, wishlistIds]);

  const [ownedIds, setOwnedIds] = useState<Set<string>>(new Set());
  // Real in-game acquisition date per owned variant (from
  // CollectionState.json -> ServerState.Cards[].TimeCreated), distinct from
  // when a card was added to a list in this app.
  const [acquisitionDates, setAcquisitionDates] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  // Bumped by the "Retry" button to re-run the load effect.
  const [reloadNonce, setReloadNonce] = useState(0);
  // Global toggle (Navigation) to hide the lower part of every card (name,
  // badge, info) across all pages, not just a single card.
  const [hideCardDetails, setHideCardDetails] = useState(() => {
    return localStorage.getItem('marvelSnapHideCardDetails') === '1';
  });
  // Held here (not in a page component) so the grid column count stays
  // applied on both routes; only the All Cards page renders its control.
  const cardColumns = useCardColumns(hideCardDetails);

  useEffect(() => {
    localStorage.setItem('marvelSnapHideCardDetails', hideCardDetails ? '1' : '0');
  }, [hideCardDetails]);

  // Load variants on mount.
  // Bulk variants come from snapCompleteService, which caches them in
  // localStorage and only re-downloads variants.json when the version
  // in variants-meta.json changes (see snapCompleteService.ts).
  // Owned variants come from public/owned-variants.json, generated by
  // `npm run import-owned` from the Marvel Snap save file
  // (CollectionState.json), and are also cached/versioned the same way.
  useEffect(() => {
    const loadVariants = async () => {
      setLoading(true);
      setLoadError(false);

      let variants: Variant[];
      try {
        variants = await snapCompleteService.getAllVariants();
      } catch {
        // No data and no usable cache - show a retryable error instead of
        // hanging on the loading screen.
        setLoadError(true);
        setLoading(false);
        return;
      }

      // Merge in cost data, when present, from public/cost-data.json
      // (generated by `npm run import-costs` from the Marvel Snap shop save).
      // Coverage is partial by nature - only variants recently seen in this
      // account's shop/vault will have this data.
      try {
        const costResponse = await fetch('/cost-data.json', { cache: 'no-store' });
        if (costResponse.ok) {
          const costFile: CostDataFile = await costResponse.json();
          const costById = new Map(costFile.entries.map((e) => [e.id, e]));
          variants = variants.map((v) => {
            const cost = costById.get(v.id);
            return cost
              ? { ...v, bundleName: cost.bundleName, goldCost: cost.goldCost, tokenCost: cost.tokenCost }
              : v;
          });
        }
      } catch {
        // No cost data available - not fatal, cards just won't show a bundle name.
      }

      setAllVariants(variants);

      // Load owned variants: prefer the freshly-imported file if present,
      // otherwise fall back to whatever was cached locally before.
      try {
        const response = await fetch('/owned-variants.json', { cache: 'no-store' });
        if (response.ok) {
          const data: OwnedVariantsFile = await response.json();
          setOwnedIds(new Set(data.ownedIds));
          localStorage.setItem('marvelSnapOwned', JSON.stringify(data.ownedIds));
          if (data.acquisitionDates) {
            setAcquisitionDates(data.acquisitionDates);
            localStorage.setItem('marvelSnapAcquisitionDates', JSON.stringify(data.acquisitionDates));
          }
        } else {
          throw new Error('owned-variants.json not found');
        }
      } catch {
        const savedOwned = localStorage.getItem('marvelSnapOwned');
        if (savedOwned) {
          setOwnedIds(new Set(JSON.parse(savedOwned)));
        }
        const savedAcquisitionDates = localStorage.getItem('marvelSnapAcquisitionDates');
        if (savedAcquisitionDates) {
          setAcquisitionDates(JSON.parse(savedAcquisitionDates));
        }
      }

      setLoading(false);
    };

    loadVariants();
  }, [reloadNonce]);

  const missingCount = allVariants.length - ownedIds.size;

  return (
    <Router>
      <div className={`app ${hideCardDetails ? 'hide-card-details' : ''}`}>
        <Navigation
          stats={
            loading || loadError
              ? undefined
              : {
                  wishlist: wishlistCount,
                  missing: missingCount,
                  owned: ownedIds.size,
                  wishlistCost,
                }
          }
          hideCardDetails={hideCardDetails}
          onToggleHideCardDetails={() => setHideCardDetails((v) => !v)}
          onRequestTab={setActiveTabId}
          badgeColors={badgeColors}
        />
        {loadError ? (
          <div className="loading load-error">
            <p>Non è stato possibile caricare i dati delle carte.</p>
            <p className="load-error-hint">
              Controlla la connessione, oppure lancia <code>aggiorna-dati.bat</code>.
            </p>
            <button onClick={() => setReloadNonce((n) => n + 1)}>Riprova</button>
          </div>
        ) : loading ? (
          <div className="loading">Loading cards...</div>
        ) : (
          <Routes>
            <Route
              path="/"
              element={
                <VariantsList
                  allVariants={allVariants}
                  ownedIds={ownedIds}
                  acquisitionDates={acquisitionDates}
                  tabs={tabs}
                  listStore={listStore}
                  statusStyles={statusStyles}
                  badgeColors={badgeColors}
                  onDeleteTab={deleteTab}
                  cardColumns={cardColumns}
                  activeTabId={activeTabId}
                  setActiveTabId={setActiveTabId}
                />
              }
            />
            <Route
              path="/unreleased"
              element={
                <UnreleasedCards
                  allVariants={allVariants}
                  listTabs={listTabs}
                  listStore={listStore}
                  statusStyles={statusStyles}
                  badgeColors={badgeColors}
                  ownedIds={ownedIds}
                />
              }
            />
            <Route
              path="/settings"
              element={
                <SettingsPage
                  allTabs={tabs.tabs}
                  listTabs={listTabs}
                  statusStyles={statusStyles}
                  badgeColors={badgeColors}
                />
              }
            />
          </Routes>
        )}
      </div>
    </Router>
  );
}

export default App;
